language: go
go:
  - 1.6
services: postgresql
before_script:
  - psql -c 'create database deckbrewtest;' -U postgres
install:
  - go build
test:
  - ./deckbrew migrate
  - ./deckbrew sync
  - go test -v ./...
