language: go
go:
  - 1.6
services: postgresql
install:
  - go build
before_script:
  - psql -c 'create database deckbrewtest;' -U postgres
  - ./deckbrew migrate
  - ./deckbrew sync
script:
  - ./scripts/test
